version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    image: towakoyama/task-management-app-backend:latest
    ports:
      - "8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0