version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Expose Redis port to host
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend 
    ports: 
       - "8002:8000"
    depends_on: 
      redis:
        condition: service_healthy
          
    environment: 
     REDIS_URL : redis://redis:6379/0 
    # 開発中はホットリロードのためにボリュームをマウントする
    # volumes:
    #   - ./backend/app:/app/app
  frontend:
    build: ./frontend 
    ports: 
     - "3000:3000"
    depends_on: 
     - backend 