version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment: 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: taskdb 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    healthcheck: 
      test: ["CMD-SHELL", "pg-isready -U user"]
      interval: 5s 
      timeout: 5s 
      retries: 5 

  backend:
    build: ./backend 
    ports: 
       - "8000:8000"
    depends_on: 
        db: 
          condition: service_healthy 
    environment: 
     DATABASE_URL : postgresql://user:password@db:5432/taskdb
    # 開発中はホットリロードのためにボリュームをマウントする
    # volumes:
    #   - ./backend/app:/app/app
  frontend:
    build: ./frontend 
    ports: 
     - "3000:3000"
    depends_on: 
     - backend 

volumes:
    postgres_data: