version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Expose Redis port to host
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    images: towakoyama/task-management-app-backend:latest
    
    ports: 
       - "8000"
    depends_on: 
      redis:
          
    environment: 
     REDIS_URL : redis://redis:6379/0 
    # 開発中はホットリロードのためにボリュームをマウントする
    # volumes:
    #   - ./backend/app:/app/app
  frontend:
    image: towakoyama/task-management-app-frontend:latest 
    ports: 
     - "3000"
    depends_on: 
     - backend 