# fly.toml app configuration file generated for task-management-app-backend on 2025-09-10T16:44:11+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'task-management-app-backend'
primary_region = 'nrt'

[build]
  dockerfile = 'backend/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
