# render.yaml
services:
- type: redis
  name: redis
  plan: free
  ipAllowList:
    - source: 0.0.0.0/0
      description: Allow internal connections from all services

- type: web
  name: backend
  env: python
  plan: starter
  region: oregon # デプロイ先のリージョンを設定してください
  autoDeploy: false
  healthCheckPath: /
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
  envVars:
    - key: REDIS_URL
      value: redis://redis:6379/0

- type: web
  name: frontend
  env: node
  plan: starter
  region: oregon # デプロイ先のリージョンを設定してください
  autoDeploy: false
  buildCommand: npm install && npm run build
  startCommand: npm start
  envVars:
    - key: NEXT_PUBLIC_API_URL
      value: http://backend:8000