services:
- type: web
  name: frontend
  env: node
  plan: starter
  autoDeploy: false
  buildCommand: npm install && npm run build
  startCommand: npm run start
  envVars:
    - key: NEXT_PUBLIC_API_URL
      value: http://backend:8000
- type: web
  name: backend
  env: python
  plan: starter
  autoDeploy: false
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
- type: redis
  name: redis
  plan: starter